//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectionQ3
    {
        public int Qid { get; set; }
        public string Question { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string CorrectAns { get; set; }
        public string Question_Tr { get; set; }
        public string Option1_Tr { get; set; }
        public string Option2_Tr { get; set; }
        public string Option3_Tr { get; set; }
        public string Option4_Tr { get; set; }
    }
}
