//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reply
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> MessageId { get; set; }
        public string ReplyFromUser { get; set; }
        [Required]
        public string ReplyMessage { get; set; }
        public System.DateTime ReplyDate { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
