//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sound
    {
        public int soundID { get; set; }
        public Nullable<int> quizID { get; set; }
        public Nullable<int> Q_optionID { get; set; }
        public string sound_reference { get; set; }
    }
}
