//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportQ2
    {
        public int Qid { get; set; }
        public string Question { get; set; }
        public string ans1 { get; set; }
        public string keyword1 { get; set; }
        public string keyword2 { get; set; }
        public string Question_Tr { get; set; }
    }
}
