//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> ProgressXP { get; set; }
        public Nullable<bool> quiz1 { get; set; }
        public Nullable<bool> quiz2 { get; set; }
        public Nullable<bool> quiz3 { get; set; }
        public Nullable<bool> quiz4 { get; set; }
        public Nullable<bool> quiz5 { get; set; }
        public Nullable<bool> quiz6 { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
